[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "protectionstnd"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
[tool.maturin]
features = ["pyo3/extension-module"]

[tool.maturin.metadata]
author = "Alejandro Martinez"
author_email = "aegloszenit@protonmail.com"
description = "Security Protections, from sql injection to country specific protections"
url = "https://github.com/zenitaeglos/protectionstnd.git"
license = "MIT"